[project]
name = "backend"
version = "0.1.0"
description = "ToolMe API â€” The sandbox where your projects matter."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.7",
    "uvicorn[standard]>=0.40.0",
]
